In [ ]:
# file import

In [ ]:
ctrl+?

In [1]:
import pandas as pd

In [2]:
from pandas import read_excel

In [3]:
df_demo= read_excel(r"Downloads\dataengineering_task_24Nov2025.xlsx",sheet_name="customer_demo")

In [4]:
df_demo

  custname cust_address  cust_pincode
0    param         6-43        521134
1    athma         4-32        521134
2     ravi         4-32        521134
3   rakesh         4-32        521134
4  krishna         4-32        521134
5  lakshmi         4-32        521134
6    ramya         4-32        521134
7   rajini         4-32        521134
8     ramu         4-32        521134

In [5]:
df_demo.shape

(9, 3)

In [6]:
df_demo.columns

Index(['custname', 'cust_address', 'cust_pincode'], dtype='object')

In [7]:
df_demo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   custname      9 non-null      object
 1   cust_address  9 non-null      object
 2   cust_pincode  9 non-null      int64
dtypes: int64(1), object(2)
memory usage: 344.0+ bytes

In [8]:
df_trans= read_excel(r"Downloads\dataengineering_task_24Nov2025.xlsx",sheet_name="cust_trans")

In [9]:
df_trans

   Cust_name  cust_transaction      month
0      param                 1 2025-11-01
1      param                 1 2025-11-01
2      param                 1 2025-11-01
3      param                 1 2025-11-01
4      param                 1 2025-11-01
5      param                 1 2025-11-01
6      athma                 1 2025-11-01
7      athma                 1 2025-11-01
8      athma                 1 2025-11-01
9      athma                 1 2025-11-01
10      ravi                 1 2025-11-01
11    rakesh                 1 2025-11-01
12   krishna                 1 2025-11-01
13   krishna                 1 2025-11-01
14   krishna                 1 2025-11-01
15    rajini                 1 2025-11-01
16      ramu                 1 2025-11-01
17      ramu                 1 2025-11-01
18      ramu                 1 2025-11-01
19      ramu                 1 2025-11-01
20      ramu                 1 2025-11-01
21      ramu                 1 2025-11-01
22      ramu                 1 2025-11-01
23      ramu                 1 2025-11-01
24      ramu                 1 2025-11-01

In [10]:
df_trans.Cust_name.unique()

array(['param', 'athma', 'ravi', 'rakesh', 'krishna', 'rajini', 'ramu'],
      dtype=object)

In [11]:
df_demo.custname.unique()

array(['param', 'athma', 'ravi', 'rakesh', 'krishna', 'lakshmi', 'ramya',
       'rajini', 'ramu'], dtype=object)

In [ ]:
join --summary
summary --join

In [ ]:
?

In [ ]:
df_trans

In [ ]:
cust,nooftrans

In [ ]:
import pandas as pd

# Example Transaction Table
data = {
    "custname": ["Ramesh", "Suresh", "Ramesh", "John", "Ramesh", "Suresh"],
    "transaction_date": [
        "2025-01-02", "2025-01-03", "2025-01-05",
        "2025-01-10", "2025-01-20", "2025-01-22"
    ]
}

df = pd.DataFrame(data)

In [ ]:
df

In [ ]:
df_trans.columns

In [14]:

# Convert date column (optional but recommended)
df_trans['cust_transaction'] = pd.to_datetime(df_trans['cust_transaction'])

# 🔥 Customer-wise Transaction Count
txn_count = df_trans.groupby("Cust_name").size().reset_index(name="transaction_count")

print(txn_count)

  Cust_name  transaction_count
0     athma                  4
1   krishna                  3
2     param                  6
3    rajini                  1
4    rakesh                  1
5      ramu                  9
6      ravi                  1

In [15]:
txn_count

  Cust_name  transaction_count
0     athma                  4
1   krishna                  3
2     param                  6
3    rajini                  1
4    rakesh                  1
5      ramu                  9
6      ravi                  1

In [16]:
df_demo

  custname cust_address  cust_pincode
0    param         6-43        521134
1    athma         4-32        521134
2     ravi         4-32        521134
3   rakesh         4-32        521134
4  krishna         4-32        521134
5  lakshmi         4-32        521134
6    ramya         4-32        521134
7   rajini         4-32        521134
8     ramu         4-32        521134

In [ ]:
txn_count,df_demo

In [17]:
df_final=df_demo.merge(txn_count,left_on=['custname'],right_on=['Cust_name'],how='left')

In [18]:
df_final

  custname cust_address  cust_pincode Cust_name  transaction_count
0    param         6-43        521134     param                6.0
1    athma         4-32        521134     athma                4.0
2     ravi         4-32        521134      ravi                1.0
3   rakesh         4-32        521134    rakesh                1.0
4  krishna         4-32        521134   krishna                3.0
5  lakshmi         4-32        521134       NaN                NaN
6    ramya         4-32        521134       NaN                NaN
7   rajini         4-32        521134    rajini                1.0
8     ramu         4-32        521134      ramu                9.0

In [19]:
df_final_v1=df_final[['custname','transaction_count']]

In [20]:
df_final_v1

  custname  transaction_count
0    param                6.0
1    athma                4.0
2     ravi                1.0
3   rakesh                1.0
4  krishna                3.0
5  lakshmi                NaN
6    ramya                NaN
7   rajini                1.0
8     ramu                9.0

In [22]:
df_typeofacct= read_excel(r"Downloads\dataengineering_task_24Nov2025.xlsx",sheet_name="cust_acctypeCust")

In [23]:
df_typeofacct

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Cust_name,Type of account,initial amount
0,NaN,NaN,NaN,NaN,NaN,NaN,param,sa,5000
1,NaN,NaN,NaN,NaN,NaN,NaN,athma,ca,10000
2,NaN,NaN,NaN,NaN,NaN,NaN,ravi,rd,500000
3,NaN,NaN,NaN,NaN,NaN,NaN,rakesh,fd,500000
4,NaN,NaN,NaN,NaN,NaN,NaN,krishna,sa,5000
5,NaN,NaN,NaN,NaN,NaN,NaN,lakshmi,ca,10000
6,NaN,NaN,NaN,NaN,NaN,NaN,ramya,rd,500000
7,NaN,NaN,NaN,NaN,NaN,NaN,rajini,fd,500000
8,NaN,NaN,NaN,NaN,NaN,NaN,ramu,de,200000

In [ ]:
report --->

In [24]:
df_typeofacct.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Cust_name', 'Type of account', 'initial amount'],
      dtype='object')

In [27]:
df_typeofacct=df_typeofacct[['Cust_name', 'Type of account']]

In [28]:
df_typeofacct

  Cust_name Type of account
0     param              sa
1     athma              ca
2      ravi              rd
3    rakesh              fd
4   krishna              sa
5   lakshmi              ca
6     ramya              rd
7    rajini              fd
8      ramu              de

In [29]:
df_typeofacct.Cust_name.value_counts()

param      1
athma      1
ravi       1
rakesh     1
krishna    1
lakshmi    1
ramya      1
rajini     1
ramu       1
Name: Cust_name, dtype: int64

In [30]:
df_final_v1

  custname  transaction_count
0    param                6.0
1    athma                4.0
2     ravi                1.0
3   rakesh                1.0
4  krishna                3.0
5  lakshmi                NaN
6    ramya                NaN
7   rajini                1.0
8     ramu                9.0

In [ ]:
base,child, type, on,

In [31]:
df_trans_demo=df_final_v1.merge(df_typeofacct,how='left',left_on='custname',right_on='Cust_name')

In [32]:
df_trans_demo

  custname  transaction_count Cust_name Type of account
0    param                6.0     param              sa
1    athma                4.0     athma              ca
2     ravi                1.0      ravi              rd
3   rakesh                1.0    rakesh              fd
4  krishna                3.0   krishna              sa
5  lakshmi                NaN   lakshmi              ca
6    ramya                NaN     ramya              rd
7   rajini                1.0    rajini              fd
8     ramu                9.0      ramu              de

In [33]:
df_trans_demo.columns

Index(['custname', 'transaction_count', 'Cust_name', 'Type of account'], dtype='object')

In [35]:
df_trans_demo[['custname', 'transaction_count', 'Type of account']]

  custname  transaction_count Type of account
0    param                6.0              sa
1    athma                4.0              ca
2     ravi                1.0              rd
3   rakesh                1.0              fd
4  krishna                3.0              sa
5  lakshmi                NaN              ca
6    ramya                NaN              rd
7   rajini                1.0              fd
8     ramu                9.0              de

In [ ]:
df_trans_demo.to_excel(path,sheet_name,index=False)

In [36]:
df_trans_demo.to_excel(r'Downloads\trans_details.xlsx')

In [37]:
df_trans_demo.to_excel(r'Downloads\trans_details_index.xlsx',index=False)

In [38]:
df_trans_demo.to_csv(r'Downloads\trans_details_index_csv.csv',index=False)

In [ ]:
keep, drop

18 3 -->drop
3 18 --keep

In [ ]:
explore

In [ ]:
base
child
on
how
type

In [39]:
df_trans_demo

  custname  transaction_count Cust_name Type of account
0    param                6.0     param              sa
1    athma                4.0     athma              ca
2     ravi                1.0      ravi              rd
3   rakesh                1.0    rakesh              fd
4  krishna                3.0   krishna              sa
5  lakshmi                NaN   lakshmi              ca
6    ramya                NaN     ramya              rd
7   rajini                1.0    rajini              fd
8     ramu                9.0      ramu              de

In [40]:
df_oftrans= read_excel(r"Downloads\dataengineering_task_24Nov2025.xlsx",sheet_name="offer_trans")

In [41]:
df_oftrans

  no_of_trans  offer
0   3 or more    0.2
1     below 3    0.3

In [ ]:
flagging
tagging
new col

In [42]:
import numpy as np

In [43]:
df_oftrans['trans_cnt']=np.where(df_oftrans['no_of_trans']=='3 or more',1,0)

In [44]:
df_oftrans

  no_of_trans  offer  trans_cnt
0   3 or more    0.2          1
1     below 3    0.3          0

In [ ]:
if else

In [ ]:
where(condtion,true,false)

In [45]:
df_trans_demo

  custname  transaction_count Cust_name Type of account
0    param                6.0     param              sa
1    athma                4.0     athma              ca
2     ravi                1.0      ravi              rd
3   rakesh                1.0    rakesh              fd
4  krishna                3.0   krishna              sa
5  lakshmi                NaN   lakshmi              ca
6    ramya                NaN     ramya              rd
7   rajini                1.0    rajini              fd
8     ramu                9.0      ramu              de

In [46]:
df_trans_demo['offer']=np.where(df_trans_demo['transaction_count']>=3,0.2,0.3)

In [47]:
df_trans_demo

  custname  transaction_count Cust_name Type of account  offer
0    param                6.0     param              sa    0.2
1    athma                4.0     athma              ca    0.2
2     ravi                1.0      ravi              rd    0.3
3   rakesh                1.0    rakesh              fd    0.3
4  krishna                3.0   krishna              sa    0.2
5  lakshmi                NaN   lakshmi              ca    0.3
6    ramya                NaN     ramya              rd    0.3
7   rajini                1.0    rajini              fd    0.3
8     ramu                9.0      ramu              de    0.2

In [48]:
df_trans_demo[df_trans_demo['transaction_count']>=0]

  custname  transaction_count Cust_name Type of account  offer
0    param                6.0     param              sa    0.2
1    athma                4.0     athma              ca    0.2
2     ravi                1.0      ravi              rd    0.3
3   rakesh                1.0    rakesh              fd    0.3
4  krishna                3.0   krishna              sa    0.2
7   rajini                1.0    rajini              fd    0.3
8     ramu                9.0      ramu              de    0.2